import type { MetricDefinition } from "./models";

/** Versioned, deterministic registry. Source evidence is intentionally human-auditable. */
export const metricRegistry: readonly MetricDefinition[] = [
  { metricId: "people.employee_count", name: "Employees", domain: "people", source: "users", calculation: "count active users", period: "daily", filters: ["status=active", "departmentId", "role"], permission: ["Owner", "Admin", "Manager"], sensitivity: "internal", freshness: "24 hours", aggregation: "count", sourceEvidence: ["users.status", "users.institutionId", "users.departmentId", "users.role"] },
  { metricId: "workforce.employee_count", name: "Employees", domain: "workforce", source: "users", calculation: "count active users", period: "daily", filters: ["status=active"], permission: ["Owner", "Admin", "Manager"], sensitivity: "internal", freshness: "24 hours", aggregation: "count", sourceEvidence: ["users.status", "users.institutionId"] },
  { metricId: "task.completion_rate", name: "Task completion rate", domain: "task", source: "tasks", calculation: "done tasks / all tasks * 100", period: "weekly", filters: ["status", "departmentId", "role"], permission: ["Owner", "Admin", "Manager", "Employee"], sensitivity: "internal", freshness: "24 hours", aggregation: "ratio", sourceEvidence: ["tasks.status", "tasks.institutionId", "tasks.departmentId", "tasks.assignedTo"] },
  { metricId: "operations.task_completion_rate", name: "Task completion rate", domain: "operations", source: "tasks", calculation: "done tasks / all tasks * 100", period: "weekly", filters: ["status"], permission: ["Owner", "Admin", "Manager", "Employee"], sensitivity: "internal", freshness: "24 hours", aggregation: "ratio", sourceEvidence: ["tasks.status", "tasks.institutionId", "tasks.departmentId"] },
  { metricId: "inventory.low_stock", name: "Low stock items", domain: "inventory", source: "inventoryItems", calculation: "count items where currentQuantity <= minimumLevel", period: "daily", filters: ["departmentId", "locationId", "category"], permission: ["Owner", "Admin", "Manager"], sensitivity: "internal", freshness: "24 hours", aggregation: "count", sourceEvidence: ["inventoryItems.currentQuantity", "inventoryItems.minimumLevel", "inventoryItems.institutionId", "inventoryItems.locationId"] },
  { metricId: "operations.inventory_low_stock", name: "Low stock items", domain: "operations", source: "inventoryItems", calculation: "count items where currentQuantity <= minimumLevel", period: "daily", filters: ["departmentId", "locationId"], permission: ["Owner", "Admin", "Manager"], sensitivity: "internal", freshness: "24 hours", aggregation: "count", sourceEvidence: ["inventoryItems.currentQuantity", "inventoryItems.minimumLevel", "inventoryItems.institutionId"] },
  { metricId: "financial.revenue", name: "Finalized revenue", domain: "financial", source: "payments", calculation: "sum finalized payment transactionAmount", period: "monthly", filters: ["status", "departmentId", "module", "locationId", "category"], permission: ["Owner", "Admin", "Manager"], sensitivity: "confidential", freshness: "24 hours", aggregation: "sum", sourceEvidence: ["payments.status", "payments.transactionAmount", "payments.institutionId"] },
  { metricId: "resource.utilization", name: "Resource utilization", domain: "resource", source: "healthcareResources", calculation: "occupied capacity / total capacity * 100", period: "daily", filters: ["departmentId", "locationId"], permission: ["Owner", "Admin", "Manager"], sensitivity: "internal", freshness: "24 hours", aggregation: "ratio", sourceEvidence: ["healthcareResources.capacity", "healthcareResources.available", "healthcareResources.institutionId"] },
  { metricId: "operational.active_work", name: "Active operational work", domain: "operational", source: "tasks", calculation: "count tasks not done", period: "daily", filters: ["status", "departmentId", "module"], permission: ["Owner", "Admin", "Manager", "Employee"], sensitivity: "internal", freshness: "24 hours", aggregation: "count", sourceEvidence: ["tasks.status", "tasks.institutionId", "tasks.departmentId"] },
  { metricId: "workflow.pending_approvals", name: "Pending approvals", domain: "workflow", source: "approvals", calculation: "count submitted or under review approvals", period: "daily", filters: ["status", "departmentId", "role"], permission: ["Owner", "Admin", "Manager"], sensitivity: "confidential", freshness: "24 hours", aggregation: "count", sourceEvidence: ["approvals.status", "approvals.institutionId", "approvals.departmentId"] },
  { metricId: "compliance.security_events", name: "Security events", domain: "compliance", source: "securityEvents", calculation: "count security events in period", period: "monthly", filters: ["category", "role", "departmentId"], permission: ["Owner", "Admin"], sensitivity: "restricted", freshness: "24 hours", aggregation: "count", sourceEvidence: ["securityEvents.type", "securityEvents.institutionId", "securityEvents.createdAt"] },
  { metricId: "module.healthcare_patients", name: "Healthcare patients", domain: "module", source: "patientIdentities", calculation: "count active patient identities", period: "monthly", filters: ["departmentId", "locationId"], permission: ["Owner", "Admin", "Manager", "Clinician", "Nurse", "Reception", "Billing"], sensitivity: "confidential", freshness: "24 hours", aggregation: "count", sourceEvidence: ["patientIdentities.status", "patientIdentities.institutionId"] },
  { metricId: "governance.approval_cycle_time", name: "Approval cycle time", domain: "governance", source: "approvals", calculation: "average approvedAt - submittedAt", period: "monthly", filters: ["status", "departmentId"], permission: ["Owner", "Admin", "Manager"], sensitivity: "confidential", freshness: "24 hours", aggregation: "average", sourceEvidence: ["approvals.status", "approvals.submittedAt", "approvals.approvedAt"] },
];

export function getMetric(metricId: string) {
  return metricRegistry.find((metric) => metric.metricId === metricId);
}

export function canReadMetric(metric: MetricDefinition, role: string) {
  return metric.permission.includes(role as MetricDefinition["permission"][number]);
}
