"use client";
import { useEffect, useState } from "react";
import { Activity, AlertTriangle, CheckCircle2 } from "lucide-react";
import { Card } from "@/components/ui/card";
import { EmptyState, ErrorState, LoadingState, PageHeader, SummaryMetrics } from "@/components/shared/page-shell";
import { useAuth } from "@/lib/auth-context";
import type { OperationalCue, OperationalLoad, ReadinessMatrix, ScenarioSimulation } from "@/lib/operational-intelligence";
type Response = { loads: OperationalLoad[]; cues: OperationalCue[]; readiness: ReadinessMatrix; simulations: ScenarioSimulation[] };
export default function OperationalIntelligencePage() {
  const { profile, loading } = useAuth(); const [data, setData] = useState<Response | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!profile) return; fetch("/api/operational-intelligence").then(async (r) => { if (!r.ok) throw new Error((await r.json()).error); return r.json(); }).then(setData).catch((e: unknown) => setError(e instanceof Error ? e.message : "Unable to load operational intelligence.")); }, [profile]);
  if (loading) return <LoadingState label="Loading operational intelligence…" />; if (!profile) return <EmptyState title="Sign in to view operational intelligence" description="This workspace is scoped to your institution." />; if (error) return <ErrorState message={error} />; if (!data) return <LoadingState label="Evaluating operational signals…" />;
  return <div><PageHeader title="Operational intelligence" description="Deterministic operational signals from business, audit, telemetry, and UI events. No automatic reassignment or generative recommendations." /><SummaryMetrics items={[{ label: "Load state", value: data.loads[0]?.state ?? "normal" }, { label: "NOW", value: data.cues.filter((c) => c.lane === "NOW").length }, { label: "Readiness", value: data.readiness.overall }, { label: "Scenarios", value: data.simulations.length }]} /><div className="mt-6 grid gap-4 lg:grid-cols-2"><Card className="p-5"><h2 className="flex items-center gap-2 font-semibold text-ink"><Activity size={18} className="text-accent" />NOW / NEXT / ATTENTION</h2><div className="mt-4 space-y-3">{data.cues.length ? data.cues.map((cue) => <div key={cue.cueId} className="rounded border border-line p-3"><div className="flex justify-between"><span className="text-xs font-semibold text-accent">{cue.lane}</span><span className="text-xs text-muted">{cue.priority}</span></div><p className="mt-1 font-medium text-ink">{cue.title}</p><p className="text-sm text-muted">{cue.detail}</p></div>) : <p className="text-sm text-muted">No operational signals recorded.</p>}</div></Card><Card className="p-5"><h2 className="flex items-center gap-2 font-semibold text-ink"><CheckCircle2 size={18} className="text-accent" />Readiness matrix</h2><p className="mt-2 text-sm text-muted">Evidence-backed status: {data.readiness.overall}</p><div className="mt-4 space-y-2">{data.readiness.cells.map((cell) => <div key={cell.dimension} className="flex justify-between rounded border border-line p-3"><span className="text-sm text-ink">{cell.dimension}</span><span className="text-xs text-muted">{cell.status}</span></div>)}</div></Card></div>{data.loads.some((l) => l.state === "blocked") ? <p className="mt-4 flex items-center gap-2 text-sm text-warning"><AlertTriangle size={16} />Blocked load requires human review.</p> : null}</div>;
}
