"use client";
import Link from "next/link";
import { useState } from "react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import { SectionHeading } from "@/components/shared/section-heading";
import { useAuth } from "@/lib/auth-context";
import { deactivateDepartment, saveDepartment, useDepartments, useEmployees } from "@/lib/firebase/data";

export default function DepartmentsPage() {
  const { profile } = useAuth(); const { data, loading } = useDepartments(profile?.institutionId); const { data: people } = useEmployees(profile?.institutionId);
  const [status, setStatus] = useState("active"); const [editing, setEditing] = useState<string | null>(null); const [form, setForm] = useState({ name: "", departmentCode: "", description: "", headUserId: "" });
  const canManage = profile?.role === "Owner" || profile?.role === "Admin"; const canEdit = (id: string) => canManage || (profile?.role === "Manager" && profile.departmentId === id && data.find((department) => department.departmentId === id)?.headUserId === profile.uid);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!profile) return; await saveDepartment({ ...form, headUserId: form.headUserId || null }, profile.institutionId, editing ?? undefined); setEditing(null); setForm({ name: "", departmentCode: "", description: "", headUserId: "" }); window.location.reload(); };
  return <div><SectionHeading eyebrow="Workspace" title="Departments" description="Organize people and work by institution department." />{(canManage || editing) && <Card className="mb-5 p-5"><form onSubmit={(e) => void submit(e)} className="grid gap-3 md:grid-cols-2"><Input required placeholder="Department name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /><Input required placeholder="Code" value={form.departmentCode} onChange={(e) => setForm({ ...form, departmentCode: e.target.value })} /><Input placeholder="Description" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /><select className="h-9 rounded-md border border-line bg-surface px-3 text-sm text-ink" value={form.headUserId} onChange={(e) => setForm({ ...form, headUserId: e.target.value })}><option value="">No department head</option>{people.filter((p) => p.role === "Manager").map((p) => <option key={p.uid} value={p.uid}>{p.fullName}</option>)}</select><div className="flex gap-2"><Button className="bg-accent text-white" type="submit">{editing ? "Save changes" : "Create department"}</Button>{editing && <Button type="button" onClick={() => setEditing(null)}>Cancel</Button>}</div></form></Card>}{!canManage && <p className="mb-4 text-sm text-muted">Managers can edit only their own headed department.</p>}<div className="mb-4 flex gap-2"><Button onClick={() => setStatus("active")} className={status === "active" ? "border-accent text-accent" : ""}>Active</Button><Button onClick={() => setStatus("inactive")} className={status === "inactive" ? "border-accent text-accent" : ""}>Inactive</Button></div>{loading ? <p className="text-sm text-muted">Loading departments…</p> : <div className="grid gap-4 md:grid-cols-2">{data.filter((d) => d.status === status).map((department) => { const head = people.find((p) => p.uid === department.headUserId); return <Card className="p-5" key={department.departmentId}><div className="flex items-start justify-between"><div><Link href={`/departments/${department.departmentId}`} className="text-lg font-semibold text-ink hover:text-accent">{department.name}</Link><p className="mt-1 text-xs uppercase tracking-wider text-muted">{department.departmentCode}</p></div><Badge>{department.status}</Badge></div><p className="mt-4 text-sm text-muted">{department.description || "No description"}</p><p className="mt-4 text-xs text-muted">Head: {head?.fullName ?? "Unassigned"}</p>{canEdit(department.departmentId) && <div className="mt-4 flex gap-2"><Button onClick={() => { setEditing(department.departmentId); setForm({ name: department.name, departmentCode: department.departmentCode, description: department.description, headUserId: department.headUserId ?? "" }); }}>Edit</Button>{canManage && department.status === "active" && <Button onClick={() => void deactivateDepartment(department.departmentId).then(() => window.location.reload())}>Deactivate</Button>}</div>}</Card>; })}</div>}</div>;
}
